### PR TITLE
Update lecture3.tex

### PR DESCRIPTION
**Pull request by SaharCarmel**
I think there is a forgotten "Length of" for defining Lj. Also i think that the equation is more elaborate as also shown in lecture

### CODE REVIEW

**Comment by avivt** [comment]
Hi Sahar,

Can you please check that the latex on line 43-46 compiles? I think you're missing a \right

Aviv

**Comment by SaharCarmel** [comment]
Fixed it

**Comment by avivt** [comment]
it still gives me an error. Can you please check (e.g., on Overleaf) that the equation compiles?

**Comment by SaharCarmel** [comment]
image

**Comment by avivt** [comment]
Hi Sahar,

The formula as written is not accurate. What it should be is: if there is no i<j with a_i<a_j then L_j=1, otherwise L+j is \max {L_i:i<j, a_i<a_j}+1.

**Comment by SaharCarmel** [comment]
image
Like so?

**Comment by avivt** [comment]
yes, that's better!

**Comment by SaharCarmel** [comment]
Done.

**Comment by avivt** [comment]
Thank you!

**Pull request merged**
